before_install:
        - wget -q http://www.cmake.org/files/v3.14/cmake-3.14.5-Linux-x86_64.tar.gz && tar xzf cmake-3.14.5-Linux-x86_64.tar.gz -C $HOME
        - export CMAKE_COMMAND=$HOME/cmake-3.14.5-Linux-x86_64/bin/cmake
#        - export MAKE_COMMAND="make -j4 install VERBOSE=1 \&\& make test ARGS=\"-V\""

matrix:
  include:
    - language: cpp
      os: linux
      dist: xenial
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-7
          - libeigen3-dev
          - libboost1.58-all
          - libasound2-dev
          - python3-numpy
          - maven
      
      env: PYTHON_HOME=/usr
           PATH=/usr/lib/jvm/java-8-openjdk-amd64/jre/bin:$PATH
           CXX=g++-7 
           PLATFORM=Linux

    - language: cpp
      os: linux
      dist: xenial
      compiler: gcc
      addons:
        apt:
          packages:
          - maven
      
      before_script:
      - wget https://releases.linaro.org/components/toolchain/binaries/7.3-2018.05/armv8l-linux-gnueabihf/gcc-linaro-7.3.1-2018.05-x86_64_armv8l-linux-gnueabihf.tar.xz
      - tar xf gcc-linaro-7.3.1-2018.05-x86_64_armv8l-linux-gnueabihf.tar.xz -C $HOME
      - wget https://dl.bintray.com/boostorg/release/1.68.0/source/boost_1_68_0.tar.gz
      - tar xf boost_1_68_0.tar.gz -C $HOME
      - cd $HOME/boost_1_68_0
      - ./bootstrap.sh
      - ./b2 clean
      - "echo \"using gcc : arm : $HOME/gcc-linaro-7.3.1-2018.05-x86_64_armv8l-linux-gnueabihf/bin/armv8l-linux-gnueabihf-g++ ;\" >> project-config.jam"
      - ./b2 toolset=gcc-arm -j8 -d2 cxxflags=-fPIC cflags=-fPIC --without-python link=static threading=multi threadapi=pthread define=BOOST_MATH_DISABLE_FLOAT128
      - cd $HOME
      - export BOOST_ROOT=$HOME/boost_1_68_0
      - wget http://bitbucket.org/eigen/eigen/get/3.3.4.tar.bz2
      - tar jxf 3.3.4.tar.bz2 -C $HOME
      - export EIGEN_ROOT=$HOME/eigen-eigen-5a0156e40feb
      - mkdir $HOME/alsa
      - wget http://archive.raspberrypi.org/debian/pool/main/a/alsa-lib/libasound2_1.1.3-5+rpt4_armhf.deb
      - ar x libasound2_1.1.3-5+rpt4_armhf.deb
      - tar xf data.tar.xz -C $HOME/alsa
      - wget http://archive.raspberrypi.org/debian/pool/main/a/alsa-lib/libasound2-dev_1.1.3-5+rpi3_armhf.deb
      - ar x libasound2-dev_1.1.3-5+rpi3_armhf.deb
      - tar xf data.tar.xz -C $HOME/alsa
      - wget http://raspbian.mirror.constant.com/raspbian/pool/main/o/openjdk-8/openjdk-8-jdk_8u222-b10-1~deb9u1_armhf.deb
      - ar x openjdk-8-jdk_8u222-b10-1~deb9u1_armhf.deb
      - mkdir $HOME/jdk
      - tar xf data.tar.xz -C $HOME/jdk
      - wget http://raspbian.mirror.constant.com/raspbian/pool/main/o/openjdk-8/openjdk-8-jre-headless_8u222-b10-1~deb9u1_armhf.deb
      - ar x openjdk-8-jre-headless_8u222-b10-1~deb9u1_armhf.deb
      - mkdir $HOME/jre
      - tar xf data.tar.xz -C $HOME/jre
      - mkdir $HOME/pydev
      - wget http://raspbian.raspberrypi.org/raspbian/pool/main/p/python3.5/libpython3.5_3.5.3-1+deb9u1_armhf.deb
      - ar x libpython3.5_3.5.3-1+deb9u1_armhf.deb
      - tar xf data.tar.xz -C $HOME/pydev 
      - wget http://raspbian.raspberrypi.org/raspbian/pool/main/p/python3.5/libpython3.5-dev_3.5.3-1+deb9u1_armhf.deb
      - ar x libpython3.5-dev_3.5.3-1+deb9u1_armhf.deb
      - tar xf data.tar.xz -C $HOME/pydev 
      - wget http://raspbian.raspberrypi.org/raspbian/pool/main/p/python-numpy/python3-numpy_1.12.1-3_armhf.deb
      - ar x python3-numpy_1.12.1-3_armhf.deb
      - tar xf data.tar.xz -C $HOME/pydev 
      - wget http://raspbian.raspberrypi.org/raspbian/pool/main/e/expat/libexpat1_2.2.0-2+deb9u2_armhf.deb
      - ar x libexpat1_2.2.0-2+deb9u2_armhf.deb
      - tar xf data.tar.xz -C $HOME/pydev 
      - mkdir $HOME/zlib
      - wget http://raspbian.raspberrypi.org/raspbian/pool/main/z/zlib/zlib1g-dev_1.2.8.dfsg-5_armhf.deb
      - ar x zlib1g-dev_1.2.8.dfsg-5_armhf.deb
      - tar xf data.tar.xz -C $HOME/zlib 
      - wget http://raspbian.raspberrypi.org/raspbian/pool/main/z/zlib/zlib1g_1.2.8.dfsg-5_armhf.deb
      - ar x zlib1g_1.2.8.dfsg-5_armhf.deb
      - tar xf data.tar.xz -C $HOME/zlib 
      - export CMAKE_ARGS="-DZLIB_ROOT=$HOME/zlib/usr -DZLIB_LIBRARY=$HOME/zlib/lib/arm-linux-gnueabihf/libz.so.1 -DPYTHON_LIBRARY=$HOME/pydev/usr/lib/arm-linux-gnueabihf/libpython3.5m.so -DPYTHON_INCLUDE_DIR=$HOME/pydev/usr/include/python3.5m -DGODEC_ADDITIONAL_INCLUDE_DIRS=$HOME/pydev/usr/lib/python3.5m/numpy/\;$HOME/pydev/usr/include -DGODEC_ADDITIONAL_LINKER_DIRS=$HOME/pydev/lib/arm-linux-gnueabihf -DBOOST_INCLUDEDIR=$BOOST_ROOT -DBOOST_LIBRARYDIR=$BOOST_ROOT/stage/lib/ -DEigen3_INCLUDE_DIRS=$EIGEN_ROOT -DALSA_LINKER_DIR=$HOME/alsa/usr/lib/arm-linux-gnueabihf -DALSA_INCLUDE_DIRS=$HOME/alsa/usr/include -DJNI_INCLUDE_DIRS=\"$HOME/jdk/java-8-openjdk-armhf/include/;$HOME/jdk/java-8-openjdk-armhf/include/linux\" -DJAVA_JVM_LIBRARY=$HOME/jre/usr/lib/jvm/java-8-openjdk-armhf/jre/lib/arm/client/libjvm.so"
      - cd $TRAVIS_BUILD_DIR

      env: PYTHON_HOME=$HOME/pydev/usr
           PATH=/usr/lib/jvm/java-8-openjdk-amd64/jre/bin:$PATH
           CXX=$HOME/gcc-linaro-7.3.1-2018.05-x86_64_armv8l-linux-gnueabihf/bin/armv8l-linux-gnueabihf-g++ 
           PLATFORM=Generic_ARM

    - language: android
      dist: trusty
      addons:
        apt:
          packages:
          - maven
          - bzip2
      before_script:
      - wget https://dl.google.com/android/repository/android-ndk-r18b-linux-x86_64.zip
      - unzip -q android-ndk-r18b-linux-x86_64.zip -d $HOME
      - export ANDROID_NDK_HOME=$HOME/android-ndk-r18b
      - export PATH=$PATH:$ANDROID_NDK_HOME
      - mkdir "$ANDROID_HOME/licenses" || true		
      - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"		
      - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"	
      - $ANDROID_NDK_HOME/build/tools/make_standalone_toolchain.py --arch arm --api 21 --install-dir $HOME/android-clang-toolchain
      - export CXX=$HOME/android-clang-toolchain/bin/arm-linux-androideabi-clang++
      - wget https://github.com/Manromen/Boost-for-Android/releases/download/Boost-1.68.0_2/boost-android-r18b-armeabi-v7a-1.68.0.zip
      - mkdir "$HOME/boost" || true		
      - unzip -q boost-android-r18b-armeabi-v7a-1.68.0.zip -d $HOME/boost
      - export BOOST_ROOT=$HOME/boost
      - wget http://bitbucket.org/eigen/eigen/get/3.3.4.tar.bz2
      - tar jxf 3.3.4.tar.bz2 -C $HOME
      - export EIGEN_ROOT=$HOME/eigen-eigen-5a0156e40feb
      - export CMAKE_ARGS="-DBoost_NO_SYSTEM_PATHS=ON -DBOOST_INCLUDEDIR=$BOOST_ROOT/include/ -DBOOST_LIBRARYDIR=$BOOST_ROOT/lib/armeabi-v7a -DEigen3_INCLUDE_DIRS=$EIGEN_ROOT"
      - echo no | android create avd --force --name test --target android-22 --abi armeabi-v7a
      - emulator -avd test -no-skin -no-audio -no-window -gpu off -no-boot-anim &
      - android-wait-for-emulator
      - adb shell input keyevent 82 &
      android:
        components:
          - tools
          - platform-tools
          - build-tools-26.0.2
          - android-22
          - android-26
          - sys-img-armeabi-v7a-android-22  
      env: PYTHON_HOME=/usr
           PATH=/usr/lib/jvm/java-7-openjdk-amd64/jre/bin:$PATH
           PLATFORM=Android

script:
       -  mkdir cmake-build && cd cmake-build && $HOME/cmake-3.14.5-Linux-x86_64/bin/cmake -DPLATFORM=$PLATFORM $CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=../install ../ && make -j4 install VERBOSE=1 && make test ARGS="-V" 
#       - mkdir cmake-build && cd cmake-build
#       - "\"$CMAKE\" -DPLATFORM=$PLATFORM $CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=../install ../"
#       - "$MAKE_COMMAND"

